language: minimal

addons:
  apt:
    packages:
    - pandoc

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always

branches:
    only:
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/